### ISSUE TITLE
Can I use delta coming from quill to update contents (delta object) with this library?

### ISSUE THREAD

**Issue by owenfar** [nadar/quill-delta-parser#83]
Hello, sorry for opening an issue about this question, but from the documentation alone I cannot figure it out. And maybe you'll be better at helping me towards the right direction - I would very much appreciate it!

The discussion started here: https://github.com/quilljs/quill/discussions/4026

In summary, I'm saving Quill content in my SQL database as a delta object. And when changes are made on the website, I want to send only the changed text (using delta from text-change event), because it's not ideal to keep sending the whole editor contents for simple changes/updates in the document.

As far as I can tell, there's nothing mentioned about this in the documentation or under quill-awesome repo that can do this. But I'm a bit stunned because how is everyone else doing it then? Send the whole getContents each time (currently I'm doing this)? Can you help me sum up this question please?

If I can use this library or contribute in some way here so that we can achieve this goal it would be great!

Thanks in advance

**Comment by nadar** [comment]
hey @owenfar i have to admit, i never was thinking about that, for all the use cases i had, it was never a problem to send the full quill json content. I assume you like to send the quill delta after each "change" to an api, which then stores this information.

If this is the case, i would just debounce the requests, so that when you type it waits for a second or two until nothing is typed anymore and then send the ajax request. 

+ https://www.geeksforgeeks.org/lodash-_-debounce-method/
+ https://www.freecodecamp.org/news/javascript-debounce-example/

i think, sadly, thats all i can help here. I also don't like quill and delta, use prosemirror with tiptap, its so much better 😄  if you need a php parser for that as well, i did one https://github.com/nadar/prosemirror-json-parser

**Comment by owenfar** [comment]
Hello @nadar, thank you for your reply. Yes I already do the debounce :) 

I was actually looking into alternatives just because of this. My use-case is a bit like Dropbox Paper, so imagine if you have a large document, and you just want to add a punctuation or a small update. To send the whole document each time kind of hurts me a little 😄 Because I did my best for my app to have as small requests as possible.

Now that you mentioned it, I will have another look at ProseMirror.

Appreciate your time to look into this! All the best
